### PR TITLE
Storybook : Add Crop- Details Component

### PR DESCRIPTION
**Pull request by mahieakhtar**
Feature add crop component

### CODE REVIEW

**Comment by mahieakhtar** [comment]
Done, Thanks Gizem

**Comment by senner007** [comment]
There are some files with extentions that end with 1, like js1 and ccs1. What are those for?

**Comment by mahieakhtar** [comment]
I have renamed the folder and file back and forth as it was suggested by Gizem to use kebab-case.

**Comment by mahieakhtar** [comment]
kindly confirm, do we need to update our local branch with develop branch so as to have the latest changes? I see build failure at pull request which doesn't happen at my end. And maybe I have tried install which might have updated the package.json. The changes made on server might be because of prettier. 
Kindly suggest me here

**Comment by gizemcandemir** [comment]
> Done, Thanks Gizem
:pray:
Btw, remember Zaki suggested to have this file naming convention; to add `.component` to the component's file name. So your component files should be renamed for example as `add-crop.component.js` instead of `add-crop.js`

**Comment by mahieakhtar** [comment]
> > Done, Thanks Gizem
> 
> 🙏
> Btw, remember Zaki suggested to have this file naming convention; to add `.component` to the component's file name. So all your component files should be renamed. For example as
> `add-crop.component.js` instead of `add-crop.js`

Done ,Thanks Gizem

**Comment by bytewiz** [comment]
Still there is a lot of unrelated changes on this branch :)

**Pull request merged**
