### PR TITLE
test: add storybook to tests

### PR DESCRIPTION
**Pull request by zkwsk**
This will automatically test that storybook can build on each PR.

### CODE REVIEW

**Comment by zkwsk** [comment]
Lol... waiting for #126 to be merged so I can see if it actually runs Storybook :)

**Comment by ricardoaguiar** [comment]
Hey Zaki, 
Do we need to do anything on this branch?

**Comment by zkwsk** [comment]
@ricardoaguiar yes, please review :)

**Comment by MirSzabo** [comment]
Hi Zaki I looked on Storybook CLI utilities documentation to understand the code you added and looks fine to me and I can run storybook

**Pull request merged**
