### PR TITLE
Revert "Storybook : Add Crop- Details Component"

### PR DESCRIPTION
**Pull request by dpfernandes**
Reverts HackYourFuture-CPH/FP-class11#71

Add Crop is now called Add Batch so this needs to be reverted

@mahieakhtar will make a new PR with the changes that we need

### CODE REVIEW

**Comment by bytewiz** [comment]
@dpfernandes @mahieakhtar If it is just the naming that changed we should just make a new Pull Request that renames it instead that will be less work IMO 👍

**Comment by dpfernandes** [comment]
@bytewiz, we already have the new PR for this https://github.com/HackYourFuture-CPH/FP-class11/pull/113

Can't we just Revert and Merge PR#113?

**Comment by mahieakhtar** [comment]
> @dpfernandes @mahieakhtar If it is just the naming that changed we should just make a new Pull Request that renames it instead that will be less work IMO 👍


Hi Niels,
 These are the new requirement which changed on Add Batch field:
1>Crop Name changed from input field to dropdown.
2>Deleted the Harvest Date field from the form.

**Comment by dpfernandes** [comment]
This will be solved on PR #113

**Pull request closed without merging**
