### PR TITLE
Feature/logout

### PR DESCRIPTION
**Pull request by Nazaqat**

### CODE REVIEW

**Comment by senner007** [comment]
Didn't I add comments to to this pr. some time ago?

**Comment by Nazaqat** [comment]
> Didn't I add comments to to this pr. some time ago?

Hi Niels, I tried to make it simple but code did not work because I have installed reactjs-popup package to work this code may be?

**Comment by senner007** [comment]
Maybe somewhat like this :
```
import React from 'react';
import Popup from 'reactjs-popup';

const userName = 'Servet';

export default function Logout() {
  
  const popupView = (closeAction) => (
    <PopupModal title={"LOG OUT"} closeAction={closeAction}>
      <LogoutContent>
        <LogoutActions closeAction={closeAction}></LogoutActions> 
     </LogoutContent> 
    </PopupModal>
  );

  return (
    <Popup
      trigger={PopupTrigger}
      modal="true"
    >
      {popupView}
    </Popup>
  );
}

const PopupTrigger = () => (
  <button type="submit" className="logout-button">
    LOG OUT
  </button>
);


const PopupModal = ({closeAction, children, title}) => {
  return (
    <div className="modal">
      <button type="submit" className="close" onClick={closeAction}>
        &times;
      </button>
      <div className="header">{title}</div>
      {children}
    </div>
  )
}

const LogoutContent = ({children}) => {
  return (
    <>
      <div className="content">
        <p>
          Hi {userName} <br />
          Do you really want to Logout ?{' '}
        </p>
      </div>
      {children}
    </>
  )
}

const LogoutActions = ({closeAction}) => (
  <div className="actions">
    <button
      className="confirm-logout"
      type="submit"
      onClick="location.href='/login?dis=yes'"
    >
      Logout
    </button>
    <br />
    <button
      type="submit"
      className="confirm-cancel"
      onClick={() => {
        closeAction();
      }}
    >
      Cancel
    </button>
  </div>
);
```

**Comment by Nazaqat** [comment]
Hi Niels, Thank you for help. Let me try this code and return you back asap. 
Med venlig hilsen/ Best regards,
Nazaqat Ali
Tel: +45 5363 7061
E-mail: naa.dk@yahoo.com 

    Den søndag den 29. marts 2020 14.24.11 CEST skrev Niels Theil Gregersen <notifications@github.com>:  
 
 


Maybe somewhat like this :
import React from 'react';
import Popup from 'reactjs-popup';

const userName = 'Servet';

export default function Logout() {
  
  const popupView = (closeAction) => (
    <PopupModal title={"LOG OUT"} closeAction={closeAction}>
      <LogoutContent>
        <LogoutActions closeAction={closeAction}></LogoutActions> 
     </LogoutContent> 
    </PopupModal>
  );

  return (
    <Popup
      trigger={PopupTrigger}
      modal="true"
    >
      {popupView}
    </Popup>
  );
}

const PopupTrigger = () => (
  <button type="submit" className="logout-button">
    LOG OUT
  </button>
);


const PopupModal = ({closeAction, children, title}) => {
  return (
    <div className="modal">
      <button type="submit" className="close" onClick={closeAction}>
        &times;
      </button>
      <div className="header">{title}</div>
      {children}
    </div>
  )
}

const LogoutContent = ({children}) => {
  return (
    <>
      <div className="content">
        <p>
          Hi {userName} <br />
          Do you really want to Logout ?{' '}
        </p>
      </div>
      {children}
    </>
  )
}

const LogoutActions = ({closeAction}) => (
  <div className="actions">
    <button
      className="confirm-logout"
      type="submit"
      onClick="location.href='/login?dis=yes'"
    >
      Logout
    </button>
    <br />
    <button
      type="submit"
      className="confirm-cancel"
      onClick={() => {
        closeAction();
      }}
    >
      Cancel
    </button>
  </div>
);

**Comment by bytewiz** [comment]
@Nazaqat What is the status of this?!

**Comment by Nazaqat** [comment]
ll be updated  new

**Pull request closed without merging**
